@Api_HostAddress = https://localhost:7082

### Registreer een nieuwe gebruiker
POST {{Api_HostAddress}}/api/user/register
Content-Type: application/json

{
  "username": "NathanvdDieren",
  "email": "nathan@example.com",
  "password": "MijnVeiligWachtwoord123!"
}
### Log een gebruiker in
POST {{Api_HostAddress}}/api/user/login
Content-Type: application/json

{
"email": "nathan@example.com",
"password": "MijnVeiligWachtwoord123!"
}
### Maak een nieuwe groep aan
POST {{Api_HostAddress}}/api/group/create
Content-Type: application/json

{
"name": "nathan@example.com",
"emails": ["nathan@example.com", "nathanvdieren@gmail.com"]
}

### 3. Test MET cookie (Dit moet nu "Het werkt!" en de username teruggeven)
GET {{Api_HostAddress}}/api/user/test
Accept: application/json