<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

    <PropertyGroup>
        <FrontendRoot>..\..\frontend</FrontendRoot>
        <FrontendBuildOutput>$(FrontendRoot)\dist</FrontendBuildOutput>
    </PropertyGroup>


    <Target Name="BuildFrontend" BeforeTargets="Build;Publish">

        <Exec Command="bash -i -c 'node --version'" ContinueOnError="true" IgnoreExitCode="true">
            <Output TaskParameter="ExitCode" PropertyName="NodeExitCode" />
        </Exec>
        <Error Condition="$(NodeExitCode) != 0" Text="Node.js v20+ is vereist. Controleer je installatie." />

        <Message Importance="high" Text="--- Frontend: Dependencies installeren ---" />
        <Exec Command="bash -i -c 'npm install'" WorkingDirectory="$(FrontendRoot)" />

        <Message Importance="high" Text="--- Frontend: Artifact bouwen ---" />
        <Exec Command="bash -i -c 'npm run build'" WorkingDirectory="$(FrontendRoot)" />

        <Message Importance="high" Text="--- Frontend: Bestanden kopiëren naar API wwwroot ---" />
        <ItemGroup>
            <FrontendFiles Include="$(FrontendBuildOutput)\**\*.*" />
        </ItemGroup>

        <Copy SourceFiles="@(FrontendFiles)"
              DestinationFiles="@(FrontendFiles->'wwwroot\%(RecursiveDir)%(Filename)%(Extension)')"
              SkipUnchangedFiles="true" />
    </Target>


    <Target Name="CleanFrontend" AfterTargets="Clean">
        <RemoveDir Directories="wwwroot" />
    </Target>

    <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\Application\Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Persistence\Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\assets\index-CcwT0Vzn.js" />
    <_ContentIncludedByDefault Remove="wwwroot\assets\index-CV6lL_Rq.css" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
