@Api_HostAddress = https://localhost:7082

### Registreer een nieuwe gebruiker
POST {{Api_HostAddress}}/api/users
Content-Type: application/json

{
  "userName": "NathanvdDieren",
  "email": "nathan@example.com",
  "password": "MijnVeiligWachtwoord123!"
}
